name: Build and Deploy Backend

on:
  push:
    branches: [main]
    tags:
      - "v*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/alibabaclone-backend:${{ github.ref_name }} .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/alibabaclone-backend:${{ github.ref_name }}

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            docker pull ${{ secrets.DOCKER_USERNAME }}/alibabaclone-backend:${{ github.ref_name }}

            docker stop alibabaclone-back || true
            docker rm alibabaclone-back || true

            docker run -d --name alibabaclone-back \
              -p 5000:80 \
              -e JWT_KEY="${{ secrets.JWT_KEY }}" \
              -e JWT_ISSUER="${{ secrets.JWT_ISSUER }}" \
              -e CONNECTION_STRING="${{ secrets.CONNECTION_STRING }}" \
              -e CORS_ORIGIN="${{ secrets.CORS_ORIGIN }}" \
              ${{ secrets.DOCKER_USERNAME }}/alibabaclone-backend:${{ github.ref_name }}
